#!/usr/bin/env bash
set -eu

if [ ! -d docker-elk ]; then
    git clone https://github.com/reside-ic/docker-elk
else
    git -C docker-elk pull
fi

export VAULT_ADDR=https://vault.dide.ic.ac.uk
vault login -method=github
ELASTIC_PASSWORD=$(vault read -field=value /secret/logs/elastic_password)

find docker-elk -type f -print0 | \
    xargs -0 sed -i "s/changeme/$ELASTIC_PASSWORD/g"

vault read -field=key secret/logs/ssl > ssl/key.pem
vault read -field=cert secret/logs/ssl > ssl/certificate.pem
