#!/usr/bin/env bash
set -eu

if [ ! -d docker-elk ]; then
    git clone https://github.com/reside-ic/docker-elk
else
    git -C docker-elk pull
fi

export VAULT_ADDR=https://vault.dide.ic.ac.uk:8200
vault login -method=github

ELASTIC_PASSWORD=$(vault read -field=password /secret/logs/users/elastic)
KIBANA_PASSWORD=$(vault read -field=password /secret/logs/users/kibana)
LOGSTASH_PASSWORD=$(vault read -field=password /secret/logs/users/logstash_system)

# find docker-elk -type f -print0 | \
#     xargs -0 sed -i "s/changeme/$ELASTIC_PASSWORD/g"

sed -i "/ELASTIC_PASSWORD/d" docker-elk/docker-compose.yml

sed -i "s/username: elastic/username: kibana/g" \
    docker-elk/kibana/config/kibana.yml
sed -i "s/password: changeme/password: $KIBANA_PASSWORD/g" \
    docker-elk/kibana/config/kibana.yml

sed -i "s/username: elastic/username: logstash_system/g" \
    docker-elk/logstash/config/logstash.yml
sed -i "s/password: changeme/password: $LOGSTASH_PASSWORD/g" \
    docker-elk/logstash/config/logstash.yml
sed -i "s/changeme/$ELASTIC_PASSWORD/g" \
    docker-elk/logstash/pipeline/logstash.conf

mkdir -p ssl
vault read -field=key secret/logs/ssl > ssl/key.pem
vault read -field=cert secret/logs/ssl > ssl/certificate.pem
